### ISSUE TITLE
Rename project to 'eslint-config-schibsted'

### ISSUE THREAD

**Issue by ivarconr** [schibsted/eslint-config-spt#22]
In order to clearly indicate that this is intended to be a base for all Schibsted teams/sites/projects I purpose to rename this project to `eslint-config-schibsted`. 

If you agree: :+1: 
If you disagree: :-1: 

# Tasks:
- [x] Make a PR updating the docs, `package.json`
- [x] Rename this repo
- [x] Update the NPM registry https://github.com/schibsted/eslint-config-spt 
- [x] Test that everything is still working fine with references to the old repo

**Comment by ivarconr** [comment]
I see @Andersos already have reservered "https://www.npmjs.com/package/eslint-config-schibsted". I will ask him to give me access on that repo as he has left Schibsted! 

Does Schibsted have a npm Organization?

**Comment by Andersos** [comment]
We had the @Schibsted org on NPM but nobody is paying for it now. I was also using [@schibstedbot](https://www.npmjs.com/~schibstedbot). I reserved the shorter version [eslint-config-sch](https://www.npmjs.com/package/eslint-config-sch) as well.

**Comment by ivarconr** [comment]
the npm package could also be named `@schibsted/eslint-config`. Might be better to scope it to make it clear that it is meant to solve our problems.

**Comment by alexewerlof** [comment]
I added a few tasks at the top of this issue into @ivarconr 's text. Anything I'm missing?

**Comment by ivarconr** [comment]
Looks good!

**Comment by SimenB** [comment]
Rename done, PR for docs: #25

I think we should put together new rules before actually publishing (then we can get a nice v1 start)

**Comment by alexewerlof** [comment]
> I think we should put together new rules before actually publishing (then we can get a nice v1 start)

I would settle for a semi-nice rule set. We need something out of the door so we can try it in more production projects and the rules will evolve over time. Kinda "lean" way of evolving it :)

**Comment by nosilleg** [comment]
@userpixel  Evolving rules tends to annoy people.  It's the type of this that will get a lot of comments from the people that don't like the change, and if you listen to them and revert the change then a new crowd will pop up to comment on that.

If we're prepared to answer these comments then it shouldn't be a blocker.  If we're not, then I would prefer that testing config values was done in a branch.

**Comment by alexewerlof** [comment]
@ivarconr @SimenB I needed this to be done so I just published `*-shibsted` packages and put a deprecation notice on `xxx-spt` and tried it locally. Seems alright. Would you guys check if everything is fine?

**Comment by SimenB** [comment]
Sure, that's fine! We should put together a config we all agree on ASAP though

**Comment by alexewerlof** [comment]
@SimenB this config is used on [a high profile code](https://github.com/schibsted/sdk-js) that we ship to many clients and millions of users.

I only had to customize it like this:

```
{
    "env": {
        "browser": true,
        "amd": true,
        "commonjs": true
    },,
    "extends": "schibsted",
    "rules": {
        "strict": "off",
        "camelcase": ["error", {"properties": "never"}],
        "consistent-this": ["error", "that"],
        "indent": ["error", 4],
        "no-undefined": "off",
        "no-var": "off",
        "object-shorthand": "off"
    }
}
```

That `indent: 4` is gonna be changed to `2` later. If I touched that, I practically would change 99% of the codebase. 🐴 
The `no-undefined` was annoying though. I recall we had a pretty convincing chat about it the other day. 😄 

I would also vote for `"camelcase": ["error", {"properties": "never"}]` since the properties in inter-lingual APIs tend to have snake case.

`"object-shorthand": "off"` is because currently our base browser doesn't support it. Though if we used babel on that code-base it wouldn't be an issue.

---

Here is [the PR](https://github.com/schibsted/sdk-js/pull/69) if you're interested.

**Comment by nosilleg** [comment]
What was the `no-undefined` chat?  There's an issue with the config as-is in that you can't set undefined, and you can't set `void 0` either.

`object-shorthand` is part of the ES6 ruleset, which is included by default.  Using `env-es6-false` would turn that off.

**Comment by alexewerlof** [comment]
Just to be clear I didn't apply any of these rules. These rule
customizations are the one that I needed for the project that I'm working
on.
